---
layout: resume
title: Alison Bates Resume
---
# *Alison Bates*
Accountant, Data Scientist

<div id="webaddress">
<a href="bat19007@byui.edu">bat19007@byui.edu</a>
| <a href="www.linkedin.com/in/alison-r-ririe">My LinkedIn Profile</a>
    <a href="208.399.2258">208.399.2258</a>
</div>


## Professional Summary

*Adept at working with spreadsheets, software, and with a keen eye for detail, I've used these skills in roles such as a Tax Intern at Sutton & Simmins CPA firm, efficiently reviewing and processing over 50 tax returns daily. My background also includes enriching teaching experiences, which have helped me develop critical thinking and analyzing skills.*

## Work History

**Sutton & Simmons CPA firm - Tax Intern**  

*Rexburg, ID . `01/2024 - 04/2024`*  
- Reviewed tax returns for individuals, S corps, partnership, and Estate Planning  
- Sent 50+ tax returns a day and copy into GoFileRoom using UltraTax  
- Prepared emails and physical copies of tax returns for 50+ clients a day  
- Organized files, payment vouchers, and signature documents for those clients  


**Brigham Young University - Idaho - Accounting Tutor**  

*Rexburg, ID . `01/2023-12/2023` . `09/2024` - Current*  
- Tutored for 10+ sections of ACCTG 201 and ACCTG 202  
- Met with an average of 15-16 students a week to answer questions, explain concepts, and help prepare for exams  
- Reviewed homework assignments and quizzes to help with comprehension of the subjects

## Education

**Brigham Young University - Idaho**  
*Rexburg, ID . Expected Graduation in `12/2025`*  

**Bachelor of Science in Accounting**  
- Relevant Courses:  
   Income Tax 1 & 2  
   Intermediate Financial Accounting  
   Managerial Accounting  
   Spreadsheet Analysis  
- BYU-Idaho Jack R. and Mary Lois Wheatley Leadership Scholarship  
- GPA: 4.0  

### Skills

- Fluent in Spanish
- Familiar with UltraTax
- Beginner in Python
- Spreadsheet Analysis